version: "3"
services:
  postgres-exporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable"
    volumes:
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml
    command:
      - "--extend.query-path=/etc/postgres_exporter/queries.yaml"
    ports:
      - "9187:9187"
    networks:
      - internal

networks:
  internal:
    name: internal
    external: true
