---
- name: Build uptime kuma
  hosts: localhost
  remote_user: root
  become: true


  tasks:
    - include_tasks: tasks/check_ports.yml
      vars:
        ip_port_list:
          - ip: "stun.l.google.com"
            port: 19302
          # - ip: "stun1.l.google.com"
          #   port: 19302
          # - ip: "stun2.l.google.com"
          #   port: 19302
          # - ip: "stun3.l.google.com"
          #   port: 19302
          # - ip: "stun4.l.google.com"
          #   port: 19302
          # - ip: "localhost"
          #   port: 19302
        report_dest: "/tmp"

