---
- name: Build uptime kuma
  hosts: localhost
  remote_user: root
  become: true

  tasks:
    - name: Get artifact
      ansible.builtin.include_role:
        name: docker-install
      vars:
        # base_url: "https://example.com"
