version: "3.8"
services:
  telegraf:
   image: repo.pouchen.com/docker-proxy-group/library/telegraf:1.31.2
   container_name: telegraf
   volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/log/nginx/:/var/log/nginx/:ro
   ports:
      - "9273:9273"