version: "3"
services:
  prometheus:
    container_name: monitoring-prometheus
    image: prom/prometheus:latest
    hostname: rpi-prometheus
    restart: unless-stopped
    user: "nobody"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1y'
      # - '--web.external-url=/prometheus/'
      # - '--web.route-prefix=/prometheus/'
      # /!\ Uncomment the following line to set a size limit for the Prometheus database /!\
#      - '--storage.tsdb.retention.size=10GB'
    networks:
      - internal
    expose:
      - 9090
    volumes:
      # /!\ To be modified depending on your needs /!\
      - ./prometheus/data:/prometheus
      - ./prometheus:/etc/prometheus/
    # depends_on:
    #   - cadvisor
    #   - node-exporter
    # links:
    #   - cadvisor:cadvisor
    #   - node-exporter:node-exporter

networks:
  internal:
    name: internal
    external: true
